export const cardThemes: { [key: string]: { [key: string]: string[] } } = {
    codeVibesTheme: {
        card_16: [
            '<img src= "/project/assets/img/angular_card.svg" alt="Angular">',
            '<img src= "/project/assets/img/bootstrap_card.svg" alt="Bootstrap">',
            '<img src= "/project/assets/img/css_card.svg" alt="CSS">',
            '<img src= "/project/assets/img/database_card.svg" alt="Database">',
            '<img src= "/project/assets/img/django_card.svg" alt="Django">',
            '<img src= "/project/assets/img/git_card.svg" alt="Git">',
            '<img src= "/project/assets/img/github_card.svg" alt="Github">',
            '<img src= "/project/assets/img/typeScript_card.svg" alt="Typescript">',

        ],

        card_24: [
            '<img src= "/project/assets/img/angular_card.svg" alt="Angular">',
            '<img src= "/project/assets/img/bootstrap_card.svg" alt="Bootstrap">',
            '<img src= "/project/assets/img/css_card.svg" alt="CSS">',
            '<img src= "/project/assets/img/database_card.svg" alt="Database">',
            '<img src= "/project/assets/img/django_card.svg" alt="Django">',
            '<img src= "/project/assets/img/git_card.svg" alt="Git">',
            '<img src= "/project/assets/img/github_card.svg" alt="Github">',
            '<img src= "/project/assets/img/typeScript_card.svg" alt="Typescript">',
            '<img src= "/project/assets/img/html_card.svg" alt="HTML">',
            '<img src= "/project/assets/img/javaScript_card.svg" alt="Javascript">',
            '<img src= "/project/assets/img/python_card.svg" alt="Python">',
            '<img src= "/project/assets/img/react_card.svg" alt="React">',

        ],

        card_36: [
            '<img src= "/project/assets/img/angular_card.svg" alt="Angular">',
            '<img src= "/project/assets/img/bootstrap_card.svg" alt="Bootstrap">',
            '<img src= "/project/assets/img/css_card.svg" alt="CSS">',
            '<img src= "/project/assets/img/database_card.svg" alt="Database">',
            '<img src= "/project/assets/img/django_card.svg" alt="Django">',
            '<img src= "/project/assets/img/git_card.svg" alt="Git">',
            '<img src= "/project/assets/img/github_card.svg" alt="Github">',
            '<img src= "/project/assets/img/typeScript_card.svg" alt="Typescript">',
            '<img src= "/project/assets/img/html_card.svg" alt="HTML">',
            '<img src= "/project/assets/img/javaScript_card.svg" alt="Javascript">',
            '<img src= "/project/assets/img/python_card.svg" alt="Python">',
            '<img src= "/project/assets/img/react_card.svg" alt="React">',
            '<img src= "/project/assets/img/sass_card.svg" alt="Sass">',
            '<img src= "/project/assets/img/vite_card.svg" alt="Vite">',
            '<img src= "/project/assets/img/terminal_card.svg" alt="Terminal">',
            // '<img src= "/project/assets/img/vue_card.svg" alt="Vue">',
            '<img src= "/project/assets/img/nodejs_card.svg" alt="Node.js">',
            '<img src= "/project/assets/img/supabase_card.svg" alt="Supabase">',
            '<img src= "/project/assets/img/vsCode_card.svg" alt="VS Code">'
        ]
    },

    gamingTheme: {
        card_16: ['<img src= "/project/assets/img/snake_card.svg" alt="Snake">',
            '<img src= "/project/assets/img/square_card.svg" alt="Square">',
            '<img src= "/project/assets/img/star_card.svg" alt="Star">',
            '<img src= "/project/assets/img/superMaria_card.svg" alt="Super Maria">',
            '<img src= "/project/assets/img/triangle_card.svg" alt="Triangle">',
            '<img src= "/project/assets/img/yellowPacMan_card.svg" alt="Yellow Pac-Man">',
            '<img src= "/project/assets/img/puzzel_card.svg" alt="Assassins Creed">',
            '<img src= "/project/assets/img/play_card.svg" alt="Cyberpunk">',
        ],
        card_24: [
            '<img src= "/project/assets/img/snake_card.svg" alt="Snake">',
            '<img src= "/project/assets/img/square_card.svg" alt="Square">',
            '<img src= "/project/assets/img/star_card.svg" alt="Star">',
            '<img src= "/project/assets/img/superMaria_card.svg" alt="Super Maria">',
            '<img src= "/project/assets/img/triangle_card.svg" alt="Triangle">',
            '<img src= "/project/assets/img/yellowPacMan_card.svg" alt="Yellow Pac-Man">',
            '<img src= "/project/assets/img/puzzel_card.svg" alt="puzzel">',
            '<img src= "/project/assets/img/play_card.svg" alt="play Card">',
            '<img src= "/project/assets/img/pocketNintendo_card.svg" alt="Pocket Nintendo">',
            '<img src= "/project/assets/img/pixel_card.svg" alt="Pixel">',
            '<img src= "/project/assets/img/pacMan_card.svg" alt="Pac-Man">',
            '<img src= "/project/assets/img/levelUp_card.svg" alt="Level Up">',
        ],
        card_36: [
            '<img src= "/project/assets/img/snake_card.svg" alt="Snake">',
            '<img src= "/project/assets/img/square_card.svg" alt="Square">',
            '<img src= "/project/assets/img/star_card.svg" alt="Star">',
            '<img src= "/project/assets/img/superMaria_card.svg" alt="Super Maria">',
            '<img src= "/project/assets/img/triangle_card.svg" alt="Triangle">',
            '<img src= "/project/assets/img/yellowPacMan_card.svg" alt="Yellow Pac-Man">',
            '<img src= "/project/assets/img/puzzel_card.svg" alt="puzzel">',
            '<img src= "/project/assets/img/play_card.svg" alt="play Card">',
            '<img src= "/project/assets/img/pocketNintendo_card.svg" alt="Pocket Nintendo">',
            '<img src= "/project/assets/img/pixel_card.svg" alt="Pixel">',
            '<img src= "/project/assets/img/pacMan_card.svg" alt="Pac-Man">',
            '<img src= "/project/assets/img/levelUp_card.svg" alt="Level Up">',
            '<img src= "/project/assets/img/labirint_card.svg" alt="Labirint">',
            '<img src= "/project/assets/img/cubes_card.svg" alt="Cubes">',
            '<img src= "/project/assets/img/controller_card.svg" alt="Controller">',
            '<img src= "/project/assets/img/circle_card.svg" alt="Circle">',
            '<img src= "/project/assets/img/banana_card.svg" alt="Banana">',
            '<img src= "/project/assets/img/ARoute_card.svg" alt="A Route">',
        ]
    },

    daprojectTheme: {
        card_16: [
            '<img src= "/project/assets/img/water_card.svg" alt="water_card">',
            '<img src= "/project/assets/img/tiktakto_card.svg" alt="tiktakto_card">',
            '<img src= "/project/assets/img/soup_card.svg" alt="soup_card">',
            '<img src= "/project/assets/img/shoppingbasket_card.svg" alt="shoppingbasket_card">',
            '<img src= "/project/assets/img/pokemonball_card.svg" alt="pokemonball_card">',
            '<img src= "/project/assets/img/nudelRahmen_card.svg" alt="nudelRahmen_card">',
            '<img src= "/project/assets/img/money_card.svg" alt="money_card">',
            '<img src= "/project/assets/img/kiChef_card.svg" alt="kiChef_card">',
            
        ],
        card_24: [
            '<img src= "/project/assets/img/water_card.svg" alt="water_card">',
            '<img src= "/project/assets/img/money_card.svg" alt="money_card">',
            '<img src= "/project/assets/img/kiChef_card.svg" alt="kiChef_card">',
            '<img src= "/project/assets/img/join_card.svg" alt="join_card">',
            '<img src= "/project/assets/img/flower_card.svg" alt="flower_card">',
            '<img src= "/project/assets/img/emoji_card.svg" alt="emoji_card">',
            '<img src= "/project/assets/img/tiktakto_card.svg" alt="tiktakto_card">',
            '<img src= "/project/assets/img/soup_card.svg" alt="soup_card">',
            '<img src= "/project/assets/img/shoppingbasket_card.svg" alt="shoppingbasket_card">',
            '<img src= "/project/assets/img/pokemonball_card.svg" alt="pokemonball_card">',
            '<img src= "/project/assets/img/nudelRahmen_card.svg" alt="nudelRahmen_card">',
            '<img src= "/project/assets/img/elpolloHat_card.svg" alt="elpolloHat_card">',
            
        ],
        card_36: [
            '<img src= "/project/assets/img/water_card.svg" alt="water_card">',
            '<img src= "/project/assets/img/tiktakto_card.svg" alt="tiktakto_card">',
            '<img src= "/project/assets/img/elpolloHat_card.svg" alt="elpolloHat_card">',
            '<img src= "/project/assets/img/eggs_card.svg" alt="eggs_card">',
            '<img src= "/project/assets/img/daprojects_card.svg" alt="daprojects_card">',
            '<img src= "/project/assets/img/money_card.svg" alt="money_card">',
            '<img src= "/project/assets/img/kiChef_card.svg" alt="kiChef_card">',
            '<img src= "/project/assets/img/join_card.svg" alt="join_card">',
            '<img src= "/project/assets/img/flower_card.svg" alt="flower_card">',
            '<img src= "/project/assets/img/community_card.svg" alt="community_card">',
            '<img src= "/project/assets/img/chefHat_card.svg" alt="chefHat_card">',
            '<img src= "/project/assets/img/soup_card.svg" alt="soup_card">',
            '<img src= "/project/assets/img/shoppingbasket_card.svg" alt="shoppingbasket_card">',
            '<img src= "/project/assets/img/pokemonball_card.svg" alt="pokemonball_card">',
            '<img src= "/project/assets/img/nudelRahmen_card.svg" alt="nudelRahmen_card">',
            '<img src= "/project/assets/img/emoji_card.svg" alt="emoji_card">',
            '<img src= "/project/assets/img/chat_card.svg" alt="chat_card">',
            '<img src= "/project/assets/img/arrow_card.svg" alt="arrow_card">',
        ]
    }
}